name: Shadowsocks Server (Static & Auto-Restart)

on:
  workflow_dispatch: # Позволяет запускать вручную
  repository_dispatch: # Для авторестарта
    types: [restart-shadowsocks]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 350 # 5 часов 50 минут

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          # Устанавливаем shadowsocks-libev и qrencode для QR-кода
          sudo apt-get update
          sudo apt-get install -y shadowsocks-libev qrencode

          # Скачиваем Cloudflared
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64

      - name: Generate Config and Run Services
        run: |
          # --- СТАТИЧЕСКИЕ ДАННЫЕ ДЛЯ ВЕЧНОГО КОНФИГА ---
          # !!! Можешь заменить пароль и порт на свои, если хочешь !!!
          SS_PASSWORD="YourStrongPasswordHere123"
          SS_PORT="8388"
          # Самый современный и безопасный метод шифрования
          SS_METHOD="2022-blake3-aes-128-gcm"
          
          # --- Создаем конфиг для shadowsocks-libev ---
          cat << EOF > ss-config.json
          {
              "server":"0.0.0.0",
              "server_port":${SS_PORT},
              "password":"${SS_PASSWORD}",
              "method":"${SS_METHOD}",
              "fast_open":true,
              "mode":"tcp_only"
          }
          EOF

          # --- Запускаем Shadowsocks и Cloudflared в фоновом режиме ---
          nohup ss-server -c ss-config.json &
          sleep 5
          nohup ./cloudflared-linux-amd64 tunnel run --token ${{ secrets.CF_TUNNEL_TOKEN }} &
          sleep 10

      - name: Display Connection Info
        run: |
          # --- ВСТАВЬ СЮДА СВОИ ДАННЫЕ ---
          DOMAIN="vpn.iksdev.live" # !!! ЗАМЕНИ НА СВОЙ ДОМЕН ИЗ CLOUDFLARE !!!
          SS_PASSWORD="YourStrongPasswordHere123" # !!! Пароль должен совпадать с тем, что выше !!!
          SS_METHOD="2022-blake3-aes-128-gcm"

          # --- Формируем SS URI и QR-код ---
          # Кодируем method:password в Base64
          SIP002_URI_PART=$(echo -n "${SS_METHOD}:${SS_PASSWORD}" | base64 | tr -d '\n')
          ss_uri="ss://${sip002_uri_part}@${domain}:443#github-shadowsocks"
          
          echo "========================================================================="
          echo "STATIC SHADOWSOCKS Server is ready! This config is permanent."
          echo "It will restart automatically every ~6 hours."
          echo ""
          echo "--- Connection Details ---"
          echo "Server Address: ${DOMAIN}"
          echo "Password: ${SS_PASSWORD}"
          echo "Encryption Method: ${SS_METHOD}"
          echo ""
          echo "--- SS URI (copy this and import in your client) ---"
          echo "${SS_URI}"
          echo ""
          echo "--- QR Code (SCAN THIS ONCE, IT WILL NOT CHANGE) ---"
          qrencode -t ansiutf8 "${SS_URI}"
          echo "========================================================================="
          
      - name: Keep Alive
        run: |
          sleep 20700 # ~5 часов 45 минут

      - name: Trigger Next Run (Auto-Restart)
        if: always()
        run: |
          echo "Triggering Shadowsocks restart..."
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.VDS_PAT }}" \
            "https://api.github.com/repos/${{ github.repository }}/dispatches" \
            -d '{"event_type": "restart-shadowsocks"}'
